# Generated by Django 4.0.3 on 2022-03-14 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('formFile', models.CharField(max_length=30)),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
